version: '3'
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://alex:${DB_PASSWORD}@postgres:5432/postgres
    depends_on:
      - database
      - mailhog

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025" # Mailhog web UI
      - "1025:1025" # Mailhog SMTP
  database:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
  cache:
    driver: local

